// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvbvmpsqehzldpajdnfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2YnZtcHNxZWh6bGRwYWpkbmZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NjAzNTQsImV4cCI6MjA3MTIzNjM1NH0.fW722NDzcVWxXiy-5yxc3he7RE_u9mICGmUcpbKzd8M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});